name: "Update nix sources"
on: 
  schedule:
    - cron:  '0 6 * * 2' # Every Thusday at 06: 00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=./nix
    - uses: cachix/cachix-action@v8
      with:
        name: bkkp
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Install actions
      run: nix-env -f default.nix -iA update-nix-sources

    - name: Update Nix sources
      run: update-nix-sources --reviewer kfollesdal  ${{ github.token }}
